# Welcome to Jekyll!
#

# Site settings
title: Ishan's Tech Journey
description: |
  The logcat generated as I learn, implement and develop
owner: Ishan Srivastava # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: mail.ishansrivastava@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://isriv.github.io" # the base hostname & protocol for your site
social:
  github: https://github.com/isriv
  linkedin-square: https://linkedin.com/in/<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
